---
- name: ensure sarg is installed
  apt: pkg=sarg

- name: ensure sarg.conf is configured
  template:
    src=etc/sarg/sarg.conf.j2
    dest=/etc/sarg/sarg.conf
    mode=0644
    owner=root
    group=root

- name: ensure contrab job to update sarg reports is installed
  copy:
    src=etc/cron.hourly/sarg-update
    dest=/etc/cron.hourly/sarg-update
    owner=root
    group=root
    mode=755

