---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 1080, auto_correct: true}]
  - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]
provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  group_vars_path: 'test/integration/default/groups_vars'

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    attributes:
